# Generated by Django 4.0.1 on 2023-02-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_publicapikeyaccesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicAPIKeyAccessLog',
        ),
    ]
